### ISSUE TITLE
Work Task Breakdown II

### ISSUE THREAD

**Issue by dbarry9** [fdac18/VideoFileUniqueness#10]
Daniel: Discretize frame data vectors (25-dimensional) from storage; write report.

Rayhan: Sample key frames using OpenCV.

Cole F.: Begin writing report OR validate output.

Cole S.: Create routine to insert frame data into storage given arrays of real, imag, r, g, and b values (each is a five-element array of floats) and store index of frame.

Jack: Develop PCA and k-means code.

**Comment by diadoo** [comment]
i got the basics of the K-means algorithm implemented. it takes a 2D array as input, need to talk about how it is formatted

**Comment by dbarry9** [comment]
Does the k-means algorithm still take a 2D array as input? Do you mean that it takes a two-element array (i.e. first two PC's) or a matrix-like data structure?
