### ISSUE TITLE
Storage API Error

### ISSUE THREAD

**Issue by dbarry9** [fdac18/VideoFileUniqueness#15]
python3 ./driver.py ~/
Traceback (most recent call last):
  File "./driver.py", line 34, in <module>
    idno = addDB_Vid(dbref, data[i])
  File "/home/dbarry/VideoFileUniqueness/src/storage.py", line 45, in addDB_Vid
    curs.execute(sql, newVidName)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 21 supplied.

--------------------
But I am only supplying two arguments. Is this an internal error?

**Comment by nschwerz** [comment]
The Issue seems to have been an internal error, in order to execute it needs the second argument to be in a tuple. I pushed changes that I think should fix this
