### ISSUE TITLE
Required dependecies

### ISSUE THREAD

**Issue by nschwerz** [fdac18/VideoFileUniqueness#3]

**Comment by nschwerz** [comment]
currently we need FFMPEG in order to use opencv which is not available on the hydra machines and will need to be installed on whatever machine we use

**Comment by nschwerz** [comment]
SQLite seems to be a fairly simple and easily implemented database option for us to use. It is included within the standard python libraries as of python 2.5, however there is an optional shell and an GUI that can be installed on a given machine to work with created databases

**Comment by dbarry9** [comment]
I have installed gstreamer in the Docker container.
